Carms-dev/NewcomerWerk

app/models/review.rb
review.rb
- Added validations for rating and content
=> Added validations to review model

app/models/booking.rb
=> booking validation model

app/models/service.rb
I added the validation for Service model
=> validation for the service model

app/models/user.rb, db/migrate/20200224190350_devise_create_users.rb, db/migrate/20200224210749_add_location_to_user.rb, db/schema.rb
User.rb Model
- validation added
- column location added. (you will need to db:migrate)
=> User model validation

Gemfile, Gemfile.lock, app/controllers/services_controller.rb, app/models/user.rb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/services/_form.html.erb, app/views/services/edit.html.erb, app/views/services/index.html.erb, app/views/services/new.html.erb, app/views/services/show.html.erb, db/seeds.rb
- Services Controller 7 CRUD Method
- Seed.rb for User & Service
(booking we can do so manually)
- Faker Gem is added, so *BUNDLE INSTALL* please.
=> Services crud

app/views/layouts/application.html.erb, app/views/shared/_flashes.html.erb
Added flashes, straight from the slides.
=> flashes added

app/controllers/bookings_controller.rb, app/models/booking.rb, app/views/bookings/_form.html.erb, app/views/bookings/edit.html.erb, app/views/bookings/index.html.erb, app/views/bookings/new.html.erb, app/views/services/show.html.erb, config/routes.rb
I'm going to use what carms did to test if everything work
I'm currently working in the booking controllers 
- New, create, edit and update actions
- I added new and create views with a shared partial from which I'm going to test it
=> Booking controller

app/controllers/bookings_controller.rb, app/views/bookings/index.html.erb, db/seeds.rb
- added an index for bookings 
- which displays your bookings and the bookings for you
=> added a booking index with bookings for you and by you

app/controllers/application_controller.rb, app/controllers/users_controller.rb, app/models/review.rb, app/views/services/index.html.erb, app/views/services/show.html.erb, app/views/shared/_navbar.html.erb, app/views/users/show.html.erb, config/routes.rb
- fixed profile picture display
- profile page (user#show page) based on user_id instead of current_user
- added review (received vs. written) to profile page
=> profile pic display fixed & reviews added to profile page

app/controllers/users_controller.rb, app/models/user.rb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/users/show.html.erb
Sign up fixed
- took out the validation on location
- took out non-essential fields from the sign up form
- added basic bootstrap container to sign up and edit profile form
=> Signup fix

app/controllers/services_controller.rb, app/views/services/index.html.erb, app/views/services/show.html.erb, app/views/shared/_navbar.html.erb, app/views/users/show.html.erb
- added Reviews to Service#show page
- updated navbar for profile pic (but not perfect yet)
=> added review to services

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/config/_fonts.scss, app/views/users/show.html.erb
This is a css pull about buttons, color variables and fonts added
=> Fonts colors components

app/controllers/bookings_controller.rb, app/models/booking.rb, app/views/bookings/index.html.erb, config/routes.rb, db/migrate/20200226002350_add_default_value_for_booking_status.rb, db/migrate/20200226002702_add_default_value_for_booking_completed.rb, db/schema.rb
- 2 migration generated to set default values for bookings 
1. status = 'pending', 2. completed = false
Model: 3 methods added
Controller: 3 methods added
Routes: 3 Patch paths added
Views: buttons associated are added (Accept, Decline, Mark As Complete)
*** don't forget to db:migrate ***
=> Booking status methods

app/controllers/services_controller.rb, app/javascript/packs/application.js, app/views/pages/home.html.erb
Search by title of the service
=> search a service and it gets you to the services index page

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_profile_card.scss, app/assets/stylesheets/config/_fonts.scss, app/models/user.rb, app/views/users/show.html.erb
- I changed the button and added a hover effect
- Designed the profile
- Added validation for user description of a maximum of 500 characters
=> Profile design

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/controllers/services_controller.rb, app/models/service.rb, app/views/services/_form.html.erb, app/views/services/index.html.erb
- created _card.scss
- implemented them to services#index page
=> index page cards

app/controllers/services_controller.rb, app/views/services/index.html.erb
- fixed variable
- search is now case insensitive
- search count is added
=> Search integration fix

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_service.scss, app/controllers/services_controller.rb, app/views/bookings/_form.html.erb, app/views/services/show.html.erb
- bootstrap carousel (quick and dirty)
- integrated the booking form into the page
- provider added avatar
=> Service show page css is added

app/assets/javascripts/application.js, app/assets/stylesheets/components/_card.scss, app/controllers/services_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/init_mapbox.js, app/views/services/_form.html.erb, app/views/services/index.html.erb, config/initializers/geocoder.rb, db/migrate/20200226193816_add_address.rb, db/schema.rb, db/seeds.rb, package.json, yarn.lock
- yarn add mapbox-gl
- bundle install
- added map with no style
=> map with the marquer

app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb, package.json, yarn.lock
=> home page improved

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/config/_fonts.scss, app/views/bookings/_form.html.erb
book now button changed
- class button-solid added
=> book now button done

app/assets/stylesheets/components/_button.scss, app/controllers/bookings_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/flatpickr.js, app/views/bookings/_form.html.erb, app/views/layouts/application.html.erb, package.json, yarn.lock
=> new datetime picker

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_modal.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_service.scss, app/controllers/bookings_controller.rb, app/javascript/components/modal.js, app/javascript/packs/application.js, app/models/user.rb, app/views/bookings/_form.html.erb, app/views/services/show.html.erb
Summary
- fix the div bug
- added a modal for the book now button (redirect to dashboard)
- moved the provider info up.
***didn't do the review*** pending clem's tabs.
=> Booking confirm redirect to dashboard

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_map.scss, app/controllers/services_controller.rb, app/javascript/plugins/init_mapbox.js, app/views/bookings/index.html.erb, app/views/services/_info_window.html.erb, app/views/services/index.html.erb, db/seeds.rb
- changed the width of the map 
- margin: 0px 15px 15px 15px; added this line in the cards-long
- changed the icons of the marker 
- when you hover on a service it shows in the map
- when you click on a marker there is pop-up I wanted to wait for you so that we decide what best to put for now there is only the name of the service
- I changed the address in the seeds for the ones that has one to montreal so it could work
--> so you have to db:seed
- Don't worry if in the all services there is only 5 it's just in the service controller I changed the method index to @services = Service.geocoded (it was @services = Service.all) so that only the one who has an address shows
---> we have to change the addresses in the seeds so that in the map it zooms in where we are they all have to be in …
=> Improving map

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_home.scss, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar_home.html.erb
- made the banner full page
- Added transparent navbar for just the home page.
- some changes in navbar buttons (Some # ones to window dress)
=> home page banner change

app/assets/stylesheets/components/_card.scss, app/views/services/index.html.erb
index page added banner
Card align with profile card
=> index page polished

app/assets/stylesheets/components/_review.scss, app/javascript/plugins/init_tabs.js, app/views/users/show.html.erb
Added javascript for reviews and css for styles
=> Added Javascript and fixed tabs styling profile reviews.

app/controllers/bookings_controller.rb, app/views/bookings/_incoming_card.html.erb, app/views/bookings/_outgoing_card.html.erb, app/views/bookings/index.html.erb, app/views/bookings/update_card.js.erb
=> preventing the page to reload

app/assets/stylesheets/pages/_dashboard.scss, app/views/bookings/_incoming_card.html.erb, app/views/bookings/_outgoing_card.html.erb
- added the border effect when accepted.
- added the link back to the service when click on the image of the card.
=> dashboard cards front-end done

app/assets/stylesheets/pages/_dashboard.scss
=> minor bug fix

app/assets/stylesheets/pages/_dashboard.scss, app/views/bookings/_incoming_card.html.erb, app/views/bookings/_outgoing_card.html.erb, app/views/bookings/index.html.erb, app/views/bookings/update_card.js.erb
- moved the completed button to outgoing booking.
- if completed, it will render the add review button instead.
- card avatar now justify content space between.
=> dashboard backend rework and linked to add review

app/assets/stylesheets/components/_form.scss, app/views/devise/sessions/new.html.erb, app/views/reviews/new.html.erb
Review form css/html is added/furnished and align with the site cards.
=> Review form front-end done

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_review.scss, app/assets/stylesheets/pages/_service.scss, app/views/bookings/_form.html.erb, app/views/services/show.html.erb, app/views/shared/_navbar.html.erb
- service show page added reviews in the lower session
=> Service page review

app/javascript/plugins/init_mapbox.js
=> map look and feel update

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_search_result.scss, app/controllers/services_controller.rb, app/javascript/plugins/init_mapbox.js, app/views/services/_info_window.html.erb, app/views/services/index.html.erb, app/views/shared/_navbar_home.html.erb, db/seeds.rb
- map fix: respond to search results + add nav buttons
- map info window updated
- minor layout adjustments
=> Search page

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_profile.scss, app/assets/stylesheets/pages/_search_result.scss, app/models/service.rb, app/views/pages/home.html.erb, app/views/shared/_service_card.html.erb, app/views/users/show.html.erb
- added screen size responsiveness
- service card reworked
=> profile page lg screen responsiveness added

app/assets/stylesheets/components/_booking_card.scss, app/assets/stylesheets/components/_container.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/_review.scss, app/assets/stylesheets/components/_service_card.scss, app/assets/stylesheets/components/_tab.scss, app/assets/stylesheets/components/_tabs.scss, app/assets/stylesheets/pages/_dashboard.scss, app/assets/stylesheets/pages/_profile.scss, app/assets/stylesheets/pages/_search_result.scss, app/controllers/bookings_controller.rb, app/javascript/plugins/init_tabs.js, app/models/booking.rb, app/views/bookings/_incoming_card.html.erb, app/views/bookings/_outgoing_card.html.erb, app/views/bookings/index.html.erb, app/views/users/show.html.erb, db/seeds.rb
Dashboard design redo
- tabs for bookings
- booking card
Other
- service card adjusted.
=> dashboard design revamp

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_container.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/pages/_booking.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_profile.scss, app/assets/stylesheets/pages/_search_result.scss, app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb, app/views/users/show.html.erb
Integrated the footer to most pages (except login & sign up)
=> footer added

app/assets/stylesheets/components/_container.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/pages/_home.scss, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
- fixed form footer overlap in mobile.
=> footer fix

app/assets/stylesheets/components/_container.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_profile.scss, app/views/services/new.html.erb
containers padding adjustment for xl screens
=> css polish

app/assets/stylesheets/components/_container.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/pages/_profile.scss, app/controllers/services_controller.rb, app/models/booking.rb, app/views/bookings/_form.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/pages/home.html.erb, app/views/services/index.html.erb, app/views/services/show.html.erb, app/views/users/show.html.erb, db/migrate/20200625165935_add_origin_to_users.rb, db/migrate/20200625170211_remove_message_from_bookings.rb, db/migrate/20200625232446_remove_completed_from_bookings.rb, db/schema.rb, db/seeds.rb
updated schema
- Booking: Remove Message | Remove Completed
- User: Add Origin
Seed preliminary redo
=> Schema update

db/seeds.rb
=> seed location fix

app/assets/stylesheets/components/_container.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_service.scss, app/views/pages/home.html.erb, app/views/services/show.html.erb
- home container adjust
- align containers for show-page (to fix the footer)
=> container align across pages

app/assets/stylesheets/components/_container.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_service.scss, app/controllers/services_controller.rb
Marker, only show that service's location
Booking form responsive
Service image height fixed
=> Service show polish

app/assets/stylesheets/pages/_service.scss
=> minor polish

app/assets/stylesheets/components/_carousel.scss, app/assets/stylesheets/components/_service_card.scss, app/javascript/components/carousel.js, app/javascript/components/modal.js, app/models/service.rb, app/views/services/_form.html.erb, app/views/shared/_service_card.html.erb
Carousel
- added responsiveness
- JS prevBtn display update based on slides
Service Card
- Image Clickable, better for mobile.
- Service photos validation.
=> Carousel continue
